### ISSUE TITLE
Basic Site Framework

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#1]
Due Date: 3/3/2020
Prerequisites: none
Estimated time: 5ε

> As this is the largest task and supports the functioning of all of our user stories, we will all complete this, pair programming as efficient and helpful. For example, Robert Detjens will write most of the JavaScript for the client side, pair programming with Felix Brucker. This task has no prerequisites, so we will start with it. One or two group members will also be in charge of setting up a CI environment that checks code function.

# Tasks

### Client
- [x] Development of statically served / generated pages
- [x] Change text color at bottom of screen to match the color of the arrow
- [x] Add user changeable light/dark theme to all pages?
- [x] Add GH link to the bottom bar?
### Server
- [x] Serves static pages
### General
- [x] CI tests that check code consistency of function.

Working branch: [basic-site-framework](https://github.com/cs361-stock-prediction/stock-predictor/tree/basic-site-framework)

**Comment by lyellread** [comment]
Creating branch `framework-server` to handle server framework construction
