### ISSUE TITLE
Search by Ticker Symbol

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#2]
Due Date: 3/4/2020
Prerequisites: #1 
Projected time: 3ε

> Lyell Read and Dominykas Zobakas will complete the server side modifications required to enable this functioning using pair programming, while Robert Detjens and Remi Kendig will complete the client-side modifications required to facilitate searching by ticker symbol, also using pair programming principles. Felix Brucker will be involved in ensuring that our CI tests are up to date and are checking both past code and new code added. This step is to be completed only once the Basic Site Framework is done, but relies on nothing else.

# Tasks

### Client
- [x] Search entry field
- [x] Results page
### Server
- [x] API / database setup
- [x] Search functionality
- [x] Performing lookup in database, generating results page
- [ ] Development of Prediction Algorithm

**Comment by lyellread** [comment]
- [ ] Change text color at bottom of screen to match the color of the arrow
- [ ] Add user changeable light/dark theme to all pages
- [ ] Add GH link to the bottom bar
