### ISSUE TITLE
Save Favorites

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#28]
Due Date: 3/10/2020
Prerequisites: Basic Site Framework, Search by Ticker Symbol, Account Login
Estimated time:3ε

# Tasks

### Client
- [ ] Create button on stock visible when logged in
- [ ] Send event to server when button is clicked
### Server
- [ ] Adds/removes stock ticker to account db entry when event received
- [ ] Checks if requested stock is saved to an account
