### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#3]
Due Date: 3/4/2020
Prerequisites: #1 
Estimated time: 3ε

> Felix Brucker and Lyell Read will handle modifications to the server-side of our implementation to facilitate account creation. Robert Detjens and Remi Kendig will be implementing the client-side changes that are required to enable users logging in. These pairs will both approach this using pair programming principles. Dominykas Zobakas will ensure that our CI tests are functioning for this step, as well as develop specific new steps to handle the new code written, to ensure its consistency of function over future steps. This step is to be completed only once the Basic Site Framework is done, but relies on nothing else.

# Tasks

### Client
- [x] Create Account page
- [x] Password Hashing
### Server
- [x] Account credential store
- [x] Creating user entry in account database

**Comment by lyellread** [comment]
Was not closed by merge #22
