### ISSUE TITLE
Similar Stock Recommendations

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#30]
Due Date: 3/14/2020
Prerequisites: Basic Site Framework, Search by Ticker Symbol, Account Login
Estimated time: 3ε

# Tasks

### Client
- [ ] Button on stock visible when logged in
- [ ] Click to toggle save or not save stock
- [ ] Changes to show if saved or not
### Server
- [ ] Adds/removes stock ticker to account db entry
- [ ] Checks if requested stock is saved to an account
