### ISSUE TITLE
Change Site Theme

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#33]
Due Date: 3/14/2020
Prerequisites: Basic Site Framework, Account Login 
Estimated time: 3ε

# Tasks

### Client
- [ ] Field on account page to change theme
### Server
- [ ] Store accounts’ themes
- [ ] Data containing site themes
