### ISSUE TITLE
Quick Account Creation

### ISSUE THREAD

**Issue by lyellread** [cs361-stock-prediction/stock-predictor#34]
Due Date: 3/14/2020
Prerequisites: Basic Site Framework, Account Creation
Estimated time: 3ε

# Tasks

### Client
- [ ] Button to create account via social media or Google account on “Create Account” page
### Server
- [ ] Google login service connection
- [ ] Creating user entry in account database
